### PR TITLE
Script improvements

### PR DESCRIPTION
**Pull request by rabidaudio**
Cleaned up, fixed, and added some features to the `mp4_converter` script:

1. rotate only applies to bin, not to gif
2. basic handling for input fps
3. added reverse flag (could be optimized in fw with a meta flag instead but this is good enough for now)
4. fixed options and improved documentation
5. improved output UI, added slient flag
6. Set up a `requirements.txt` to avoid dependency conflicts
7. removed a bunch of unused code
8. ran linters and formaters

### CODE REVIEW

**Review by johnMamish — COMMENTED** [review]
Alright we're gonna have to haggle sooner or later about coding style, conditionals without parenths give me indigestion.

Love the silent args, appreciate that. And the progress bar is great.

As well as hoisting the rotate into the right spot.

**Comment by johnMamish** [comment]
Merging this now, but going forward we should avoid investing effort in this and instead try and invest effort into bringing up the electron app GUI.

**Comment by johnMamish** [comment]
AHHH HOLY SHIT THIS PROJECT'S FIRST MERGED PR!!!!!

:tada: :tada:

**Comment by rabidaudio** [comment]
> Alright we're gonna have to haggle sooner or later about coding style, conditionals without parenths give me indigestion.

I learned a long time ago not to bikeshed over style and instead use a popular community linter with prepackaged rules. Standard.JS is a good example of this and has a good writeup about why you should do things this way. I remember I didn't like that it didn't use semicolons but I quickly got over it.

In this case I used `black` and `isort`, both essentially ubiquitous in the python world

**Pull request merged**
